#!/usr/bin/env bash
# Usage: bad extract target [destination]
# Summary: Copy build files to host
# Help: To show available values for <target>, use the built in tab completion:
#
#    bad extract <tab>
# _

set -e

# Make sure docker is running first
docker info > /dev/null 2>&1

# Provide bad completions
if [[ "$1" = "--complete" ]]; then
  docker images | grep 'bad-' | awk '{print $1'} | sed 's/bad-//'
  exit 0
fi

mkdir -p extracted

if [[ -d "extracted/$1-build" ]]; then
  rm -rf "extracted/$1-build"
fi

docker run --rm -i -v `pwd`/extracted:/host "bad-$1" cp -r "/$1-build/." \
  "/host/$1-build"

echo "Extracted $1 library files to ./extracted/$1-build"
