#!/usr/bin/env bash
# Usage: bad extract target [destination]
# Summary: Copy build files to host
# Help: To show available values for <target>, use the built in tab completion:
#
#    bad extract <tab>
# _

set -e

# Make sure docker is running first
docker info > /dev/null 2>&1

# Provide bad completions
if [[ "$1" = "--complete" ]]; then
  docker images | grep 'bad-' | awk 'BEGIN {OFS="-"} { print $1, $2}' | sed 's/bad-//'
  exit 0
fi

mkdir -p extracted

if [[ -d "extracted/$1-build" ]]; then
  rm -r "extracted/$1-build"
fi

name="${1%-*}"
tag="${1#*-}"

docker run --rm -i -v `pwd`/extracted:/host "bad-$name:$tag" \
  cp -r "/$name-build/." "/host/$name-$tag-build"

echo "Extracted $name v. $tag, library files to ./extracted/$name-$tag-build"
