#!/usr/bin/env bash
# Usage: bad extract target [destination]
# Summary: Copy build files to host
# Help: To show available values for <target>, use the built in tab completion:
#
#    bad extract <tab>
# _

set -e

# Make sure docker is running first
docker info > /dev/null 2>&1

# Provide bad completions
if [[ "$1" = "--complete" ]]; then
  docker images | grep 'bad-' | awk 'BEGIN {OFS="/"} { print $1, $2}' | sed 's/bad-//'
  exit 0
fi

mkdir -p extracted

if [[ -d "extracted/$1-build" ]]; then
  rm -r "extracted/$1-build"
fi

# The naming convention is as follows:
#
# - Anything before '/' is considered the name.
# - Anything after '/' but before a '-' is considered the version.
# - Anything after '/' and '-' and the last, is considered to be the
#   architecture string.
name="${1%/*}"
tag="${1#*/}"
version="${tag%%-*}"
arch="${tag#*-}"

#echo $name
#echo $tag
#echo $version
#echo $arch

docker run --rm -i -v `pwd`/extracted:/host "bad-$name:$tag" \
  cp -r "/$name-build/." "/host/$name-$tag-build"

echo "Extracted $arch version of $name v. $version, library files to ./extracted/$name-$tag-build"
